### ISSUE TITLE
Compiled templates JS does not work in IE7

### ISSUE THREAD

**Issue by raulfelix** [JrSchild/grunt-tmpl-compile#1]
After running the grunt task the resulting templates js file leaves a trailing comma which breaks in IE7. The example below will work in IE7 if you remove the comma after the search_view function.

```
(function(window) {
   window.Templates = {
      search_view: function(obj){
        ...
        return __p;
     },
   }
})(window);
```

**Comment by JrSchild** [comment]
Thanks for the catch. Updated the script, it should work fine now.
